/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  tutorialSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "Welcome",
    },
    {
      type: "category",
      label: "Learn",
      collapsible: true,
      collapsed: false,
      items: [
        "learn/overview",
        "learn/how-bridge-is-secured",
        "learn/sisu-mpc-bridge",
        "learn/token-swap",
        "learn/cross-chain-contract-interaction",
      ],
    },
    {
      type: "category",
      label: "More",
      collapsible: true,
      collapsed: true,
      items: ["more/timeline"],
    },
  ],
};

module.exports = sidebars;
